# Generated by Django 4.2.2 on 2023-06-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_News', '0002_remove_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
