# Generated by Django 4.2.2 on 2023-06-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("App_DC", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discuss", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="anonymous", max_length=200)),
                ("email", models.CharField(max_length=200, null=True)),
                ("topic", models.CharField(max_length=300)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("link", models.CharField(max_length=100, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="groupcontent",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupmember",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupmember",
            name="user",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="GroupContent",
        ),
        migrations.DeleteModel(
            name="GroupMember",
        ),
        migrations.AddField(
            model_name="discussion",
            name="forum",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="App_DC.forum",
            ),
        ),
    ]
